### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [roccomuso/no-ip#10]

**Comment by roccomuso** [comment]
Read the documentation on the repo homepage:

![image](https://user-images.githubusercontent.com/6730217/174667471-e3062480-65ff-4a6f-90b3-ea04d246900c.png)

This is what you gotta use.

**Comment by bphd** [comment]
This permit to renew the IP, not the domain 

Reopening

**Comment by roccomuso** [comment]
There's a captcha needed to renew the domain.
It's not the goal of this package.

**Comment by roccomuso** [comment]
Those are not reliable.

**Comment by bphd** [comment]
Nothing is reliable in anti cheat technology considering that the entire point of this technology is to defeat the cheat technology

So I think the point is to use them until it doesn't work. Like everything they perish
